# Annotation-based ST-BLR workflow
#
# Fixed-prior, learned annotation, group annotation, and continuous
# overlapping-annotation SBayesRC models are runnable through package wrappers.
#
# The MCMC settings shown here are demonstration settings. Real analyses need
# longer chains and appropriate convergence and posterior predictive checks.

# Packages -----------------------------------------------------------------

library(qgg)
library(sblr)

# Data directory setup -----------------------------------------------------

data_dir <- "C:/Users/au223366/Documents/GitHub/examples/human"
# Prepare Glist and sparse LD ----------------------------------------------

Glist <- readRDS(file = file.path(data_dir, "Glist_sparseLD_1k.RDS"))
chr <- 1
cls <- match(Glist$rsidsLD[[chr]], Glist$rsids[[chr]])
stopifnot(!anyNA(cls))

ld_prefix <- file.path(data_dir, "ld_test")

# Simulate or load multi-trait phenotype data ------------------------------

# mtsim_annotation() simulates overlapping annotations, enriches causal-marker
# sampling in selected annotations, and creates marker-specific prior values.
# Replace this simulation with phenotype and biological annotation data from
# the study if desired.
sim <- mtsim_annotation(
 Glist = Glist,
 chr = chr,
 rsids = Glist$rsidsLD[[chr]],
 nt = 3,
 n_shared = 30,
 n_specific = 10,
 n_annotations = 5,
 annotation_prob = 0.1,
 enriched_annotations = c(1, 2),
 annotation_enrichment = 5,
 base_pi = 0.001,
 enriched_pi_multiplier = 3,
 enriched_vb_multiplier = 1.5,
 h2 = c(0.4, 0.5, 0.3),
 rg = matrix(
  c(1.0, 0.7, 0.3, 0.7, 1.0, 0.5, 0.3, 0.5, 1.0),
  nrow = 3,
  byrow = TRUE
 ),
 re = 0,
 seed = 1
)
y <- as.matrix(scale(sim$y))

# Inspect the simulated annotation enrichment before model fitting.
summarize_annotation_signal(sim)

# Compute BED sufficient statistics with bed_xtx_xty() --------------------

# Runtime-heavy example.
stats <- bed_xtx_xty(
 bed_file = Glist$bedfiles[chr],
 n = Glist$n,
 cls = cls,
 af = Glist$af[[chr]][cls],
 y = y,
 scale = TRUE,
 nthreads = 4
)

# Stream sparse LD with sparseLD_stream_CSR() ------------------------------

# Runtime-heavy example. This writes disk-backed CSR files at ld_prefix.
sparseLD_stream_CSR(
 bed_files = Glist$bedfiles[chr],
 n = Glist$n,
 cls = list(cls),
 out_prefix = ld_prefix,
 rows = NULL,
 af = list(Glist$af[[chr]][cls]),
 pos_bp = NULL,
 max_distance_bp = 0,
 max_distance_variants = 0,
 r2_threshold = 0.001,
 block_size = 1024,
 nthreads = 4
)

# Use the simulated annotation matrix A -----------------------------------

# A is an m x K marker annotation matrix. Rows of A must correspond exactly
# to the marker ordering in stats and the sparse-LD files. Real analyses should
# replace sim$annot with biological annotations in the same marker order.
m <- length(cls)
marker_id <- Glist$rsidsLD[[chr]]
A <- sim$annot
rownames(A) <- marker_id
stopifnot(nrow(A) == m, identical(rownames(A), marker_id))

# Fixed marker-specific prior model ---------------------------------------

# stblr_csr_prior_annot() uses the marker-specific inclusion probabilities and
# variance multipliers generated by mtsim_annotation().
fit_prior_annot <- stblr_csr_prior_annot(
 stats = stats,
 ld_prefix = ld_prefix,
 A = A,
 n = Glist$n,
 fixed_pi_marker = sim$pi_marker,
 fixed_vb_multiplier = sim$vb_multiplier,
 use_pi_marker = TRUE,
 use_vb_multiplier = TRUE,
 nit = 1000,
 nburn = 100,
 nthin = 1,
 ncores = 3,
 seed = 10
)

# Learned annotation model ------------------------------------------------

# stblr_csr_learn_annot() learns annotation effects on marker inclusion
# probabilities and, optionally, marker-effect variances. These proposal scales
# are conservative demonstration settings. Real analyses require longer chains,
# convergence checks, and posterior diagnostics.
fit_learn_annot <- stblr_csr_learn_annot(
 stats = stats,
 ld_prefix = ld_prefix,
 A = A,
 n = Glist$n,
 learn_pi_annot = TRUE,
 learn_vb_annot = TRUE,
 rw_sd_eta_pi = 0.02,
 rw_sd_eta_vb = 0.02,
 annot_update_every = 10,
 nit = 1000,
 nburn = 100,
 nthin = 1,
 ncores = 3,
 seed = 10
)

# Group annotation model --------------------------------------------------

# group is a length-m marker group vector in the same order as stats and the
# sparse LD. These are conservative demonstration settings. Real analyses
# require longer chains, convergence checks, and posterior diagnostics.
group <- ifelse(A[, 1] != 0, "annotated", "background")
names(group) <- rownames(A)

fit_group_annot <- stblr_csr_group_annot(
 stats = stats,
 ld_prefix = ld_prefix,
 group = group,
 n = Glist$n,
 group_names = c("annotated", "background"),
 group_pi_init = c(0.002, 0.001),
 group_vb_multiplier_init = c(1.1, 1.0),
 updatePi = TRUE,
 updateGroupVb = TRUE,
 nit = 1000,
 nburn = 100,
 nthin = 1,
 ncores = 3,
 seed = 10
)

# SBayesRC-style annotation model -----------------------------------------

# stblr_csr_sbayesrc_generic() uses continuous overlapping annotations to
# model SBayesRC-style mixture-component probabilities. These are conservative
# demonstration settings. Real analyses require longer chains, convergence
# checks, and posterior diagnostics.
fit_sbayesrc <- stblr_csr_sbayesrc_generic(
 stats = stats,
 ld_prefix = ld_prefix,
 A = A,
 n = Glist$n,
 gamma = c(0, 0.01, 0.1, 1),
 nit = 1000,
 nburn = 100,
 nthin = 1,
 ncores = 3,
 seed = 10
)

# Inspect posterior summaries ---------------------------------------------

# Printed summaries are deliberately compact because marker-level posterior
# matrices can contain tens of thousands of rows. Full matrices remain
# available in fit$bm, fit$dm, fit$b, and other fit components.
compact_fit_summary <- function(fit, model_name) {
 bm <- as.matrix(fit$bm)
 dm <- as.matrix(fit$dm)
 trait_names <- colnames(dm)
 if (is.null(trait_names)) trait_names <- paste0("T", seq_len(ncol(dm)))

 mean_trace <- function(name) {
  x <- fit[[name]]
  if (is.null(x)) return(rep(NA_real_, ncol(dm)))
  x <- as.matrix(x)
  if (ncol(x) != ncol(dm)) return(rep(NA_real_, ncol(dm)))
  colMeans(x, na.rm = TRUE)
 }

 covariance_summary <- do.call(
  rbind,
  lapply(c("covb", "covg", "cove", "rb", "rg", "re"), function(name) {
   x <- fit[[name]]
   if (is.null(x)) return(NULL)
   x <- as.matrix(x)
   if (nrow(x) != ncol(x) || any(!is.finite(x))) return(NULL)
   off_diagonal <- x[row(x) != col(x)]
   data.frame(
    matrix = name,
    mean_diagonal = mean(diag(x)),
    mean_abs_off_diagonal = if (length(off_diagonal)) {
     mean(abs(off_diagonal))
    } else {
     NA_real_
    },
    stringsAsFactors = FALSE
   )
  })
 )

 list(
  trait_summary = data.frame(
   model = model_name,
   trait = trait_names,
   n_markers = nrow(dm),
   n_traits = ncol(dm),
   pip_sum = colSums(dm, na.rm = TRUE),
   mean_abs_bm = colMeans(abs(bm), na.rm = TRUE),
   mean_vbs = mean_trace("vbs"),
   mean_vgs = mean_trace("vgs"),
   mean_ves = mean_trace("ves"),
   row.names = NULL,
   stringsAsFactors = FALSE
  ),
  covariance_summary = covariance_summary
 )
}

top_marker_summary <- function(fit, trait = 1, top_n = 10) {
 bm <- as.matrix(fit$bm)
 dm <- as.matrix(fit$dm)
 trait_index <- if (is.character(trait)) match(trait, colnames(dm)) else trait
 if (length(trait_index) != 1 || is.na(trait_index) ||
     trait_index < 1 || trait_index > ncol(dm)) {
  stop("trait must identify one column of fit$dm.")
 }
 marker <- rownames(dm)
 if (is.null(marker)) marker <- paste0("V", seq_len(nrow(dm)))
 trait_name <- colnames(dm)[trait_index]
 if (is.null(trait_name)) trait_name <- paste0("T", trait_index)

 out <- data.frame(
  marker = marker,
  trait = trait_name,
  pip = dm[, trait_index],
  abs_bm = abs(bm[, trait_index]),
  bm = bm[, trait_index],
  stringsAsFactors = FALSE
 )
 out <- out[order(-out$pip, -out$abs_bm), , drop = FALSE]
 utils::head(out, top_n)
}

annotation_model_summary <- function(sim, fit, model_name) {
 if (!exists("summarize_annotation_signal", mode = "function")) {
  stop("summarize_annotation_signal() is required for annotation summaries.")
 }
 out <- summarize_annotation_signal(sim, fit)
 keep <- c(
  "annotation", "size", "n_causal", "causal_rate_in_set",
  grep("^(mean_dm_|mean_abs_bm_)", names(out), value = TRUE)
 )
 out <- out[, intersect(keep, names(out)), drop = FALSE]
 out$model <- model_name
 out[, c("model", setdiff(names(out), "model")), drop = FALSE]
}

fits <- list(
 fixed_prior = fit_prior_annot,
 learned_annotation = fit_learn_annot,
 group_annotation = fit_group_annot,
 sbayesrc = fit_sbayesrc
)

for (model_name in names(fits)) {
 cat("\nCompact fit summary:", model_name, "\n")
 print(compact_fit_summary(fits[[model_name]], model_name))
 cat("\nTop 10 markers for trait 1:", model_name, "\n")
 print(top_marker_summary(fits[[model_name]], trait = 1, top_n = 10))
}

for (model_name in c("fixed_prior", "learned_annotation", "group_annotation")) {
 cat("\nAnnotation signal summary:", model_name, "\n")
 print(annotation_model_summary(sim, fits[[model_name]], model_name))
}

# These optional diagnostics use helper functions from exploratory SBayesRC
# workflows when they are available in the current R session.
sbayesrc_helpers <- c(
 "sbayesrc_annotation_pi",
 "sbayesrc_annotation_gamma_mean",
 "sbayesrc_marker_gamma_mean"
)
if (all(vapply(sbayesrc_helpers, exists, logical(1), mode = "function")) &&
    !is.null(fit_sbayesrc$alpha)) {
 gamma <- c(0, 0.01, 0.1, 1)
 trait_names <- names(fit_sbayesrc$alpha)
 if (is.null(trait_names)) {
  trait_names <- paste0("T", seq_along(fit_sbayesrc$alpha))
 }

 annotation_gamma <- data.frame(
  annotation = rownames(fit_sbayesrc$alpha[[1]]),
  stringsAsFactors = FALSE
 )
 marker_gamma_summary <- list()
 marker_gamma_pip_correlation <- numeric(length(fit_sbayesrc$alpha))

 for (t in seq_along(fit_sbayesrc$alpha)) {
  marker_gamma <- sbayesrc_marker_gamma_mean(A, fit_sbayesrc$alpha[[t]], gamma)
  annotation_gamma[[trait_names[t]]] <- sbayesrc_annotation_gamma_mean(
   fit_sbayesrc$alpha[[t]], gamma
  )
  marker_gamma_summary[[trait_names[t]]] <- summary(marker_gamma)
  marker_gamma_pip_correlation[t] <- stats::cor(
   marker_gamma, fit_sbayesrc$dm[, t], use = "complete.obs"
  )
 }
 names(marker_gamma_pip_correlation) <- trait_names

 cat("\nSBayesRC annotation-level expected gamma:\n")
 print(annotation_gamma)
 cat("\nSBayesRC marker expected gamma summaries:\n")
 print(marker_gamma_summary)
 cat("\nSBayesRC marker expected gamma/PIP correlations:\n")
 print(marker_gamma_pip_correlation)
}

# Real analyses require longer chains, convergence checks, and posterior
# predictive diagnostics before interpreting these compact summaries.
