root <- normalizePath(if (file.exists("DESCRIPTION")) "." else "../..",
                      winslash = "/", mustWork = TRUE)
read <- function(path) paste(readLines(file.path(root, path), warn = FALSE),
                             collapse = "\n")
sources <- paste(vapply(c(
  "R/blr-unified.R", "R/blr-extended-convergence.R",
  "R/mtblr-convergence.R", "R/mtblr-summary-chains.R",
  "src/blr_mt_default_core_impl.h", "src/blr_mt_bed_core_impl.h",
  "src/blr_mt_bed_convergence_trace_impl.h"), read, character(1)),
  collapse = "\n")
tests <- paste(vapply(c(
  "tests/testthat/test-blr-extended-covariance-diagnostics.R",
  "tests/testthat/test-blr-extended-probability-diagnostics.R",
  "tests/testthat/test-blr-extended-parameter-diagnostics.R",
  "tests/testthat/test-blr-selected-marker-diagnostics.R",
  "tests/testthat/test-stblr-annotation-backends.R",
  "tests/testthat/test-bayesr-csr-backend.R"), read,
  character(1)), collapse = "\n")
mutations <- c(
  "second R-hat implementation", "second ESS implementation",
  "second MCSE implementation", "auto enables extended", "core captures Tier 2",
  "covariance diagonals duplicated", "covariance pair order changed",
  "B update status ignored", "E update status ignored",
  "diagonal E stochastic", "binary complement duplicated",
  "probability category order changed", "pattern names lost",
  "component names lost", "full joint enabled by default",
  "marker posterior probabilities traced", "S posterior mean used as trace",
  "fixed S stochastic", "MT sampled S accepted", "alpha order changed",
  "intercept identity lost", "updateAlpha ignored", "selected defaults to all",
  "all marker shortcut accepted", "mixed marker identity accepted",
  "marker request order lost", "b uses latent beta", "d uses component code",
  "component accepted for BayesC", "selected traces use nthin",
  "selected traces require keep_chains", "capture perturbs RNG",
  "operator preparation repeated", "chain rerun", "trace memory undercounted",
  "threshold truncates", "override warning omitted", "keep_traces changes metrics",
  "descriptor dimension mismatch", "Tier 2 under none",
  "raw schema version changed", "model semantics changed",
  "package check removed", "new model kernel",
  "ST component trace from posterior mean", "ST component order changed",
  "ST component simplex not normalized", "ST binary complement duplicated",
  "ST group trace from final state", "ST group order changed",
  "ST learned coefficient order changed", "ST intercept identity lost",
  "ST alpha schedule thins diagnostics", "ST selected b uses beta",
  "ST selected d uses component", "ST BayesC component accepted",
  "ST selected allocates all markers", "ST selected derived after aggregation",
  "ST selected capture consumes RNG", "ST capture depends on keep_chains",
  "ST capture depends on nthin", "ST trace memory omitted")
guards <- c(
  length(gregexpr(".blr_convergence_rhat_basic <- function", sources,
                  fixed = TRUE)[[1L]]) == 1L,
  grepl("one R implementation", read("docs/dev/blr_extended_diagnostics_contract.md"),
        fixed = TRUE),
  length(gregexpr("mcse_mean <- posterior_sd / sqrt(ess_mean)", sources,
                  fixed = TRUE)[[1L]]) == 1L,
  grepl("Automatic mode remains core-only", tests, fixed = TRUE) ||
    grepl("auto", sources, fixed = TRUE),
  grepl("tier = 1L", sources, fixed = TRUE),
  grepl("nt*(nt-1)/2", sources, fixed = TRUE),
  grepl("row=col+1", sources, fixed = TRUE),
  grepl("updateB", sources, fixed = TRUE), grepl("updateE", sources, fixed = TRUE),
  grepl("structural_zero", sources, fixed = TRUE),
  grepl("without its complement", tests, fixed = TRUE),
  grepl("component_names", sources, fixed = TRUE),
  grepl("pattern_name", sources, fixed = TRUE),
  grepl("component_name", sources, fixed = TRUE),
  grepl("full_probability_states = FALSE", sources, fixed = TRUE),
  grepl("marker-average", tests, fixed = TRUE),
  grepl("chain-private unthinned", tests, fixed = TRUE),
  grepl("updated = FALSE", sources, fixed = TRUE),
  grepl("sampled MT S remains unsupported",
        read("docs/dev/blr_extended_diagnostics_contract.md"), fixed = TRUE),
  grepl("for (stick", sources, fixed = TRUE),
  grepl("is_intercept", sources, fixed = TRUE),
  grepl("updateAlpha", sources, fixed = TRUE),
  grepl("selected_markers = NULL", sources, fixed = TRUE),
  grepl("shortcuts are not supported", sources, fixed = TRUE),
  grepl("must be unique marker IDs or one-based integer indices", sources,
        fixed = TRUE),
  grepl("preserve request order", tests, fixed = TRUE),
  grepl("effective marker effect", read("docs/dev/blr_extended_diagnostics_contract.md"),
        fixed = TRUE),
  grepl("binary trait activity", read("docs/dev/blr_extended_diagnostics_contract.md"),
        fixed = TRUE),
  grepl("not applicable to BayesC", sources, fixed = TRUE),
  grepl("post-burn, unthinned", read("docs/dev/blr_extended_diagnostics_contract.md"),
        fixed = TRUE),
  grepl("keep_chains", read("docs/dev/blr_extended_diagnostics_contract.md"),
        fixed = TRUE),
  grepl("diagnostic capture is RNG neutral", tests, fixed = TRUE),
  grepl("preparation remain once",
        tolower(read("docs/dev/blr_framework_phase21_report.md")), fixed = TRUE),
  grepl("rerun a chain", read("docs/dev/blr_extended_diagnostics_contract.md"),
        fixed = TRUE),
  grepl("retained <-", sources, fixed = TRUE),
  grepl("without truncation", sources, fixed = TRUE),
  grepl("proceeding because allow_large_traces", sources, fixed = TRUE),
  grepl("keep_traces FALSE/TRUE", read("docs/dev/blr_framework_phase21_report.md"),
        fixed = TRUE) || grepl("keep_traces", tests, fixed = TRUE),
  grepl("descriptor count", read("docs/dev/blr_extended_diagnostics_contract.md"),
        fixed = TRUE) || grepl("nrow(quantities)", sources, fixed = TRUE),
  grepl("mode == \"none\"", sources, fixed = TRUE),
  grepl("version = 1L", sources, fixed = TRUE),
  grepl("model_semantics_version = 2L", sources, fixed = TRUE),
  grepl("check_package.R", read(".github/workflows/blr-framework.yml"),
        fixed = TRUE),
  !grepl("phase21.*kernel", sources, ignore.case = TRUE),
  grepl("convergence_pi_task", read("src/blr_csr_bayesr_core_impl.h"), fixed = TRUE),
  grepl("component_names", sources, fixed = TRUE),
  grepl("sum", tests, fixed = TRUE),
  grepl("physical_names", read("R/blr-extended-convergence.R"), fixed = TRUE),
  grepl("convergence_group_pi", read("src/blr_csr_group_bayesc_core_impl.h"), fixed = TRUE),
  grepl("group_names", tests, fixed = TRUE),
  grepl("inclusion_coefficient", read("R/blr-extended-convergence.R"), fixed = TRUE),
  grepl("is_intercept", tests, fixed = TRUE),
  grepl("if (it>=nburn)", read("src/blr_csr_sbayesrc_core_impl.h"), fixed = TRUE),
  grepl("=b_t(marker)", read("src/blr_csr_sbayesrc_core_impl.h"), fixed = TRUE),
  grepl("component>0 ? 1 : 0", read("src/blr_csr_sbayesrc_core_impl.h"), fixed = TRUE),
  grepl("not applicable to BayesC", sources, fixed = TRUE),
  grepl("convergence_markers.size", read("src/blr_csr_bayesr_core_impl.h"), fixed = TRUE),
  grepl("convergence_trace", read("R/sparse_ld_bed_helper.R"), fixed = TRUE),
  !grepl("unif_rand|sample_uniform", read("R/blr-extended-convergence.R")),
  grepl("keep_chains || conv$compute", read("R/stblr-public.R"), fixed = TRUE),
  grepl("it >= nburn", read("src/blr_csr_bayesr_core_impl.h"), fixed = TRUE) &&
    grepl("% nthin", read("src/blr_csr_bayesr_core_impl.h"), fixed = TRUE),
  grepl("st_selected_component_trace_bytes", read("R/blr-unified.R"), fixed = TRUE))
names(guards) <- mutations
for (i in seq_along(guards)) cat(sprintf("MUTATION_%02d_%s=%s\n", i,
  gsub("[^A-Za-z0-9]+", "_", toupper(names(guards)[[i]])), guards[[i]]))
cat("PHASE21_MUTATIONS_DETECTED=", sum(guards), "\n", sep = "")
cat("PHASE21_MUTATIONS_REQUIRED=", length(guards), "\n", sep = "")
if (!all(guards)) stop("Phase 21 mutation sensitivity has undetected guards: ",
  paste(names(guards)[!guards], collapse = ", "), call. = FALSE)
