root <- normalizePath(".", winslash = "/", mustWork = TRUE)
read <- function(path) paste(readLines(file.path(root, path), warn = FALSE),
                             collapse = "\n")
contract <- read("docs/dev/blr_mt_bed_extended_convergence_contract.md")
helper <- read("tests/testthat/helper-mtblr-bed-extended-convergence-contract.R")
tests <- read("tests/testthat/test-blr-framework-phase17w.R")
workflow <- read(".github/workflows/blr-framework.yml")
has <- function(text, ...) all(vapply(list(...), grepl, logical(1), x = text,
                                      fixed = TRUE))
guards <- c(
  has(contract, "Tier 2A adds only off-diagonals", "Tier 1 diagonals are never copied"),
  has(contract, "Qoff=T*(T-1)/2"),
  has(contract, "column-major order", "column 1 with rows 2..T"),
  has(contract, "preserving fitted", "alphabetical order"),
  has(contract, "raw covariance entry", "Correlations", "deferred"),
  has(contract, "updateB=FALSE", "not_updated"),
  has(contract, "G is derived", "eligible whenever T>1"),
  has(contract, "structural_zero", "captured=FALSE"),
  has(contract, "no flags or", "solely for structural status"),
  has(contract, "Probability capture is post-update"),
  has(contract, "updatePi=FALSE", "not_updated"),
  has(contract, "physical trace key `pi_mass:null_active`"),
  has(contract, "not a second summary row", "overview count"),
  has(contract, "aliases the mass trace", "one `diagnostic_key`"),
  has(contract, "joint simplex convergence"),
  has(contract, "All-pattern scope is explicit-only", "never `auto`"),
  has(contract, "never truncated", "allow_large_traces=TRUE"),
  has(helper, "stop(\"unknown model name\")"),
  has(helper, "anyDuplicated(selection)"),
  has(contract, "order is preserved"),
  has(contract, "effective b, not latent beta"),
  has(contract, "Marker d uses", "std::int32_t"),
  has(helper, "stop(\"unknown marker ID\")"),
  has(helper, "stop(\"ambiguous marker ID\")"),
  has(helper, "marker_indices < 1L", "marker_indices > length(marker_ids)"),
  has(helper, "anyDuplicated(marker_indices)"),
  has(contract, "requested order is fixed before sampling"),
  has(contract, "not BED columns", "global Glist"),
  has(contract, "There is no posterior top-k"),
  has(contract, "All-marker", "excluded"),
  has(contract, "without jitter", "Average ranks handle ties"),
  has(contract, "constant`, not perfect convergence"),
  has(contract, "No transition-count substitution"),
  has(contract, "no shared trace buffer"),
  has(contract, "no R/Rcpp activity"),
  has(contract, "post-burn storage"),
  has(contract, "independent of compact chains"),
  has(contract, "public trace retention"),
  has(contract, "Workspace processes one scalar", "never multiplied"),
  has(contract, "Genotype and phenotype", "not diagnostic memory"),
  has(contract, "Genotype and phenotype", "not diagnostic memory"),
  has(contract, "conservatively adds", "trace copy"),
  has(contract, "Existing `fit$convergence_traces$scope`", "remain present"),
  has(contract, "Selected-marker results", "unselected markers"),
  system2("git", c("diff", "--quiet", "--", "R/mtblr-bed.R")) == 0,
  system2("git", c("diff", "--quiet", "--", "src")) == 0,
  system2("git", c("diff", "--quiet", "--", "R/RcppExports.R", "src/RcppExports.cpp")) == 0,
  system2("git", c("diff", "--quiet", "--", "DESCRIPTION", "NAMESPACE")) == 0,
  has(contract, "raw schema remain version 1"),
  !has(read("src/mtblr.cpp"), "extended_convergence"),
  !has(read("src/mtblr.cpp"), "marker_b_values"),
  has(workflow, "Rscript tools/check/check_package.R ."))
for (i in seq_along(guards)) cat(sprintf("MUTATION_%02d=%s\n", i, guards[i]))
cat("ALL_52_CRITICAL_MUTATIONS_DETECTED=", all(guards), "\n", sep = "")
stopifnot(length(guards) == 52L, all(guards))
