source(file.path("studies", "shared",
  "canonical_annotation_simulation_v1.R"), local = TRUE)

spec <- list(
  study = "12_logvar_annotation_evaluation",
  title = "Study 12: log-variance annotation evaluation",
  aspect = "aspect1_canonical_informative_annotation",
  study_version = "v1_preregistered",
  execution_status = "paused_pending_redesign",
  preregistration_date = "2026-08-09",
  preregistered_before_new_lv_results = TRUE,
  historical_data = list(
    dataset_id = "human_independent",
    qgdata_sha = "6cca5819e711d326cfb2614d7e9d9f34942612cd",
    identity_note = paste("Protected legacy fixture; not human_1000g_eur",
      "and not the current qgdata HEAD.")),
  historical_source = list(
    git_checkpoint = "7a5cbf947af9b3441538fc64d7966c693e1433f8",
    recovery = paste("Recover the pre-cleanup executable Study 12 runner and",
      "helpers from Git history only if a future redesign requires them.")),
  sblr = list(
    source = normalizePath(file.path("..", "sblr"), winslash = "/",
      mustWork = FALSE),
    sha = "2123699a9cc2e91059e7d81a745420b14eca7f6e",
    version = "0.2.0",
    local_library = file.path("results", "local",
      "12_logvar_annotation_evaluation", "rlib")),
  canonical = canonical_annotation_simulation_v1,
  arms = c(R = "SBayesR", LV = "SBayesR-LV", RC = "SBayesRC"),
  gamma = c(0, 0.01, 0.1, 1),
  initial_pi = canonical_annotation_simulation_v1$target_component_counts /
    canonical_annotation_simulation_v1$M,
  initial_h2 = 0.5,
  operator = list(
    route = "retained_block_eigen",
    representation = "low_rank",
    eigen_policy = "cumulative_positive_mass",
    eigen_prop = 0.995,
    residual_policy = "gctb_block",
    block_ve_mode = "allMixVe",
    resam_thresh = 1.1,
    minimum_ve_ratio = 0.7,
    block_ve_keep_history = TRUE,
    low_rank_residual_rebuild_every = 100L),
  mcmc = list(
    total = 9000L,
    burn = 3000L,
    retained = 6000L,
    thin = 1L,
    nchains = 4L,
    ncores = 4L,
    seeds = list(
      R = list(seed = 1206040L,
        chains = c(1206141L, 1206242L, 1206343L, 1206444L)),
      LV = list(seed = 1207040L,
        chains = c(1207141L, 1207242L, 1207343L, 1207444L)),
      RC = list(seed = 1208040L,
        chains = c(1208141L, 1208242L, 1208343L, 1208444L)))),
  priors = list(
    common = list(B = "target Vg divided by target count-weighted gamma",
      E = 1, updateB = TRUE, updateE = TRUE),
    LV = list(annotation_model = "log_variance", theta_prior_sd = 0.7,
      theta_init = 0, annotations = c("enriched_binary",
        "continuous_signal", "null_annotation"), intercept = FALSE,
      binary_transform = "center_only",
      continuous_transform = "center_and_scale_sd1"),
    RC = list(sigmaSqAlpha_a = 2, sigmaSqAlpha_b = 2,
      sigmaSqAlpha_init = c(1, 1, 1),
      intercept_prior = "proper_normal_initial_reverse_stick_mean_sd1",
      add_intercept = FALSE, standardize_annotations = FALSE,
      center_binary_annotations = FALSE, alpha_update_every = 1L,
      rationale = paste("Established Study 10 production/reference",
        "configuration; Study 11 found a=4,b=4 did not resolve mixing and",
        "the exact flat-intercept posterior encountered separation."))),
  convergence = list(theta_target_Rhat = 1.05,
    mode = "extended", keep_traces = TRUE,
    extended_groups = c("annotations", "probability"),
    aggregate_component_states = TRUE, max_trace_gb = 8),
  endpoints = c("annotation_architecture", "induced_prior_stability",
    "pip_component_architecture", "posterior_mean_beta", "prediction",
    "variance_components", "mcmc_stability", "runtime"),
  interpretation = list(
    outcome1 = paste("LV annotation inference more stable than RC with",
      "similar beta/prediction supports useful simpler parameterization."),
    outcome2 = paste("Different PIP/component architecture with similar",
      "beta/prediction implies different latent architectures and robust",
      "downstream effect estimation."),
    outcome3 = paste("Material RC beta/prediction gains support information",
      "from annotation-dependent component membership beyond variance scaling."),
    outcome4 = paste("If R matches both annotation models, this simulation",
      "does not demonstrate a major annotation-model benefit."),
    outcome5 = "Stable theta with unstable q is not successful LV inference.",
    outcome6 = paste("Separate RC raw-alpha nonconvergence from stable",
      "induced marker architecture."),
    outcome7 = paste("Unstable induced priors in both annotation models",
      "indicate difficulty not specific to SBayesRC.")),
  outputs = list(root = file.path("results", "local",
    "12_logvar_annotation_evaluation"), promote_reference = FALSE)
)
