source(file.path("studies", "shared",
  "canonical_annotation_simulation_v1.R"), local = TRUE)

spec <- list(
  study = "12_logvar_annotation_evaluation",
  title = "Study 12 Aspect 2: SBayesR-LV-generated truth",
  aspect = "aspect2_sbayesr_lv_truth_v1",
  study_version = "aspect2_v1_preregistered",
  execution_status = "paused_pending_redesign",
  preregistration_date = "2026-08-10",
  preregistered_before_truth_generation_and_fits = TRUE,
  historical_data = list(
    dataset_id = "human_independent",
    qgdata_sha = "6cca5819e711d326cfb2614d7e9d9f34942612cd",
    identity_note = paste("Protected legacy fixture; not human_1000g_eur",
      "and not the current qgdata HEAD.")),
  historical_source = list(
    git_checkpoint = "7a5cbf947af9b3441538fc64d7966c693e1433f8",
    recovery = paste("Recover the pre-cleanup executable Study 12 runner and",
      "helpers from Git history only if a future redesign requires them.")),
  sblr = list(
    source = normalizePath(file.path("..", "sblr"), winslash = "/",
      mustWork = FALSE),
    sha = "2123699a9cc2e91059e7d81a745420b14eca7f6e",
    version = "0.2.0",
    local_library = file.path("results", "local",
      "12_logvar_annotation_evaluation", "rlib")),
  canonical = canonical_annotation_simulation_v1,
  scenario = list(
    id = "sbayesr_lv_truth_v1",
    common_backbone_id = canonical_annotation_simulation_v1$id,
    theta_true = c(enriched_binary = log(3),
      continuous_signal = log(2), null_annotation = 0),
    annotation_columns = c("enriched_binary", "continuous_signal",
      "null_annotation"),
    binary_transform = "center_only",
    continuous_transform = "center_and_scale_sd1",
    annotation_intercept = FALSE,
    component_counts = c(null = 34000L, small = 500L,
      medium = 300L, large = 200L),
    allocation = "exact_count_random_permutation_independent_of_annotations",
    component_seed = 1215412L,
    effect_seed = 1215424L,
    residual = "reuse_exact_standardized_Study10_residual",
    residual_seed_provenance = 1005438L,
    h2 = 0.5,
    target_training_genetic_variance = 1,
    target_training_residual_variance = 1,
    component_independence_descriptive_limits = list(
      maximum_absolute_component_annotation_correlation = 0.10,
      maximum_absolute_active_standardized_mean_difference = 0.20),
    rc_second_moment_normalization = "arithmetic_mean_one"),
  arms = c(R = "SBayesR", LV = "SBayesR-LV", RC = "SBayesRC"),
  gamma = c(0, 0.01, 0.1, 1),
  initial_pi = c(null = 34000, small = 500, medium = 300, large = 200) /
    35000,
  initial_h2 = 0.5,
  operator = list(
    route = "retained_block_eigen", representation = "low_rank",
    eigen_policy = "cumulative_positive_mass", eigen_prop = 0.995,
    residual_policy = "gctb_block", block_ve_mode = "allMixVe",
    resam_thresh = 1.1, minimum_ve_ratio = 0.7,
    block_ve_keep_history = TRUE,
    low_rank_residual_rebuild_every = 100L),
  mcmc = list(
    total = 9000L, burn = 3000L, retained = 6000L, thin = 1L,
    nchains = 4L, ncores = 4L,
    seeds = list(
      R = list(seed = 1226040L,
        chains = c(1226141L, 1226242L, 1226343L, 1226444L)),
      LV = list(seed = 1227040L,
        chains = c(1227141L, 1227242L, 1227343L, 1227444L)),
      RC = list(seed = 1228040L,
        chains = c(1228141L, 1228242L, 1228343L, 1228444L)))),
  priors = list(
    common = list(B = "target Vg divided by target count-weighted gamma",
      E = 1, updateB = TRUE, updateE = TRUE),
    LV = list(annotation_model = "log_variance", theta_prior_sd = 0.7,
      theta_init = 0, annotations = c("enriched_binary",
        "continuous_signal", "null_annotation"), intercept = FALSE,
      binary_transform = "center_only",
      continuous_transform = "center_and_scale_sd1"),
    RC = list(sigmaSqAlpha_a = 2, sigmaSqAlpha_b = 2,
      sigmaSqAlpha_init = c(1, 1, 1),
      intercept_prior = "proper_normal_initial_reverse_stick_mean_sd1",
      add_intercept = FALSE, standardize_annotations = FALSE,
      center_binary_annotations = FALSE, alpha_update_every = 1L,
      rationale = "Exact preregistered Aspect-1 production/reference RC configuration.")),
  convergence = list(theta_target_Rhat = 1.05,
    mode = "extended", keep_traces = TRUE,
    extended_groups = c("annotations", "probability"),
    aggregate_component_states = TRUE, max_trace_gb = 8),
  decision_screen = list(
    q_truth_Pearson_min = 0.95, q_truth_Spearman_min = 0.95,
    log_q_truth_RMSE_max = 0.25,
    material_beta_correlation_gain = 0.02,
    material_validation_g_correlation_gain = 0.02,
    essentially_equal_correlation_difference = 0.01),
  endpoints = c("theta_truth_recovery", "q_truth_recovery",
    "annotation_architecture", "induced_prior_stability",
    "pip_component_architecture", "posterior_mean_beta", "prediction",
    "variance_components", "mcmc_stability", "runtime",
    "cross_aspect_synthesis"),
  interpretation = list(
    outcome_A = "LV theta/q recovery plus material gains over R supports the LV mechanism under its own truth.",
    outcome_B = "LV best under LV truth and RC best under RC truth supports architecture-dependent ranking, not universal superiority.",
    outcome_C = "RC matching or exceeding LV supports RC robustness to LV-generating-model misspecification.",
    outcome_D = "Reciprocal strong own-model advantages support genuinely different annotation mechanisms.",
    outcome_E = "R matching LV implies the registered theta signal is not strongly exploitable at these coordinates.",
    outcome_F = "Plausible theta with poor q recovery is not successful annotation recovery.",
    outcome_G = "Good q recovery with uncertain theta separates induced-architecture recovery from coefficient identifiability."),
  outputs = list(root = file.path("results", "local",
    "12_logvar_annotation_evaluation", "aspect2"),
    promote_reference = FALSE)
)
