project:
  type: website
  output-dir: "."
  render:
    - notes/*.qmd
    - methods/*.qmd

execute:
  eval: false
  freeze: true
  echo: false
  warning: false
  message: false

author:
  - name: "Peter Sørensen"
    affiliations:
      - name: "Aarhus University"
        department: "Center for Quantitative Genetics and Genomics"

website:
  title: "sblr"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Notes"
        href: notes/index.html
      - text: "Methods"
        href: methods/index.html
    right:
      - text: "GitHub"
        href: https://github.com/psoerensen/sblr

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true
    code-tools: true
    highlight-style: github
    