# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blr_phase1_validate_spec_cpp <- function(spec) {
    .Call(`_sblr_blr_phase1_validate_spec_cpp`, spec)
}

blr_phase1_validate_result_dimensions_cpp <- function(dimensions) {
    .Call(`_sblr_blr_phase1_validate_result_dimensions_cpp`, dimensions)
}

blr_phase4_scalar_tasks_cpp <- function(ntraits, nchains) {
    .Call(`_sblr_blr_phase4_scalar_tasks_cpp`, ntraits, nchains)
}

blr_phase4_scalar_seeds_cpp <- function(seed, ntraits, nchains, chain_seeds) {
    .Call(`_sblr_blr_phase4_scalar_seeds_cpp`, seed, ntraits, nchains, chain_seeds)
}

blr_phase4_retained_iterations_cpp <- function(trace_length, burnin, thinning) {
    .Call(`_sblr_blr_phase4_retained_iterations_cpp`, trace_length, burnin, thinning)
}

blr_phase5a_validate_bayesr_contract_cpp <- function(spec) {
    .Call(`_sblr_blr_phase5a_validate_bayesr_contract_cpp`, spec)
}

blr_phase7a_validate_sbayesrc_contract_cpp <- function(spec) {
    .Call(`_sblr_blr_phase7a_validate_sbayesrc_contract_cpp`, spec)
}

blr_phase9a_validate_fixed_prior_bayesc_cpp <- function(spec) {
    .Call(`_sblr_blr_phase9a_validate_fixed_prior_bayesc_cpp`, spec)
}

blr_phase9a_validate_group_bayesc_cpp <- function(spec) {
    .Call(`_sblr_blr_phase9a_validate_group_bayesc_cpp`, spec)
}

blr_phase9a_validate_learned_annotation_bayesc_cpp <- function(spec) {
    .Call(`_sblr_blr_phase9a_validate_learned_annotation_bayesc_cpp`, spec)
}

blr_phase10a_validate_scheduled_execution_cpp <- function(spec) {
    .Call(`_sblr_blr_phase10a_validate_scheduled_execution_cpp`, spec)
}

blr_phase10a_distribution_cache_diagnostic_cpp <- function(seed, threads = 2L) {
    .Call(`_sblr_blr_phase10a_distribution_cache_diagnostic_cpp`, seed, threads)
}

blr_phase10b_chain_rng_diagnostic_cpp <- function(seed, draws = 7L) {
    .Call(`_sblr_blr_phase10b_chain_rng_diagnostic_cpp`, seed, draws)
}

readLD_to_CSR_R <- function(filenameSEXP, mchrSEXP, msizeSEXP, thresholdSEXP, onebasedSEXP) {
    .Call(`_sblr_readLD_to_CSR_R`, filenameSEXP, mchrSEXP, msizeSEXP, thresholdSEXP, onebasedSEXP)
}

mtblr_cpg_omp_csr <- function(wy, ww, yy, b_init, ld_prefix, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_cpg_omp_csr`, wy, ww, yy, b_init, ld_prefix, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, seed, method)
}

bed_xtx_xty <- function(bed_file, n, cls, af, y, rows = NULL, scale = TRUE, nthreads = 1L, MG = 64L, JB = 1024L, TB = 32L) {
    .Call(`_sblr_bed_xtx_xty`, bed_file, n, cls, af, y, rows, scale, nthreads, MG, JB, TB)
}

mtblr <- function(wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr`, wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_csr_internal <- function(wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_csr_internal`, wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_csr_raw_internal <- function(wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_csr_raw_internal`, wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_eigen <- function(wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_eigen`, wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

test_read_bedfiles_to_packed_matrix <- function(bedfiles, n, rows, cls) {
    .Call(`_sblr_test_read_bedfiles_to_packed_matrix`, bedfiles, n, rows, cls)
}

test_read_bedfiles_to_dense_matrix <- function(bedfiles, n, rows, cls) {
    .Call(`_sblr_test_read_bedfiles_to_dense_matrix`, bedfiles, n, rows, cls)
}

bed_pairwise_xtx_check <- function(bed_files, n, cls, pairs, rows = NULL, af = NULL, scale = TRUE) {
    .Call(`_sblr_bed_pairwise_xtx_check`, bed_files, n, cls, pairs, rows, af, scale)
}

bed_score_from_b_check <- function(bed_files, n, cls, y, b, rows = NULL, af = NULL, scale = TRUE) {
    .Call(`_sblr_bed_score_from_b_check`, bed_files, n, cls, y, b, rows, af, scale)
}

sparseLD_thread_info <- function(nthreads = 0L) {
    .Call(`_sblr_sparseLD_thread_info`, nthreads)
}

sparseLD_stream_CSR <- function(bed_files, n, cls, out_prefix, rows = NULL, af = NULL, pos_bp = NULL, max_distance_bp = 1000000L, max_distance_variants = 1000L, r2_threshold = 0.01, block_size = 1024L, nthreads = 1L) {
    .Call(`_sblr_sparseLD_stream_CSR`, bed_files, n, cls, out_prefix, rows, af, pos_bp, max_distance_bp, max_distance_variants, r2_threshold, block_size, nthreads)
}

sparseLD_to_CSR <- function(bed_files, n, cls, rows = NULL, af = NULL, pos_bp = NULL, max_distance_bp = 1000000L, max_distance_variants = 1000L, r2_threshold = 0.01, block_size = 1024L, nthreads = 1L) {
    .Call(`_sblr_sparseLD_to_CSR`, bed_files, n, cls, rows, af, pos_bp, max_distance_bp, max_distance_variants, r2_threshold, block_size, nthreads)
}

sparseLD_write_CSR <- function(bed_files, n, cls, out_prefix, rows = NULL, af = NULL, pos_bp = NULL, max_distance_bp = 1000000L, max_distance_variants = 1000L, r2_threshold = 0.01, block_size = 1024L, nthreads = 1L) {
    .Call(`_sblr_sparseLD_write_CSR`, bed_files, n, cls, out_prefix, rows, af, pos_bp, max_distance_bp, max_distance_variants, r2_threshold, block_size, nthreads)
}

sparseLD_read_CSR <- function(prefix, one_based = TRUE) {
    .Call(`_sblr_sparseLD_read_CSR`, prefix, one_based)
}

stblr_color_blocks_from_ld <- function(sets, ld_row_ptr, ld_col_idx, ld_values, ld_col_idx_one_based = TRUE, ld_abs_threshold = 0.01, ld_r2_threshold = 0.0) {
    .Call(`_sblr_stblr_color_blocks_from_ld`, sets, ld_row_ptr, ld_col_idx, ld_values, ld_col_idx_one_based, ld_abs_threshold, ld_r2_threshold)
}

stblr_cpg_omp_csr <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, selection_s_prior_scale = NULL, estimate_selection_s = FALSE, selection_s_init = 0.0, selection_s_prior = as.numeric( c(-3.0, 2.0)), selection_s_proposal_sd = 0.35, selection_s_log_h = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, selection_s_prior_scale, estimate_selection_s, selection_s_init, selection_s_prior, selection_s_proposal_sd, selection_s_log_h)
}

stblr_cpg_omp_csr_block_eigen <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, selection_s_prior_scale = NULL, estimate_selection_s = FALSE, selection_s_init = 0.0, selection_s_prior = as.numeric( c(-3.0, 2.0)), selection_s_proposal_sd = 0.35, selection_s_log_h = NULL, bed_files = as.character( c()), n_bed = 0L, cls = NULL, rows = NULL, af = as.numeric( c()), block_start = as.integer( c()), eigen_filter = "hard_truncate", eigen_tau = 0.01, eigen_eta = 0.0) {
    .Call(`_sblr_stblr_cpg_omp_csr_block_eigen`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, selection_s_prior_scale, estimate_selection_s, selection_s_init, selection_s_prior, selection_s_proposal_sd, selection_s_log_h, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta)
}

stblr_cpg_omp_csr_annot <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, A, learn_pi_annot, learn_vb_annot, eta_pi_init, eta_vb_init, sigma_eta_pi, sigma_eta_vb, rw_sd_eta_pi, rw_sd_eta_vb, annot_update_every, pi_min, pi_max, vb_multiplier_min, vb_multiplier_max, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L) {
    .Call(`_sblr_stblr_cpg_omp_csr_annot`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, A, learn_pi_annot, learn_vb_annot, eta_pi_init, eta_vb_init, sigma_eta_pi, sigma_eta_vb, rw_sd_eta_pi, rw_sd_eta_vb, annot_update_every, pi_min, pi_max, vb_multiplier_min, vb_multiplier_max, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves)
}

stblr_cpg_omp_csr_bayesr <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start = 0L, updateE_every = 1L, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, selection_s_prior_scale = NULL, estimate_selection_s = FALSE, selection_s_init = 0.0, selection_s_prior = as.numeric( c(-3.0, 2.0)), selection_s_proposal_sd = 0.35, selection_s_log_h = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_bayesr`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, selection_s_prior_scale, estimate_selection_s, selection_s_init, selection_s_prior, selection_s_proposal_sd, selection_s_log_h)
}

stblr_cpg_omp_csr_bayesr_block_eigen <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start = 0L, updateE_every = 1L, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, selection_s_prior_scale = NULL, estimate_selection_s = FALSE, selection_s_init = 0.0, selection_s_prior = as.numeric( c(-3.0, 2.0)), selection_s_proposal_sd = 0.35, selection_s_log_h = NULL, bed_files = as.character( c()), n_bed = 0L, cls = NULL, rows = NULL, af = as.numeric( c()), block_start = as.integer( c()), eigen_filter = "hard_truncate", eigen_tau = 0.01, eigen_eta = 0.0) {
    .Call(`_sblr_stblr_cpg_omp_csr_bayesr_block_eigen`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, selection_s_prior_scale, estimate_selection_s, selection_s_init, selection_s_prior, selection_s_proposal_sd, selection_s_log_h, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta)
}

stblr_cpg_omp_csr_group_annot <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, group_index, ngroup, group_pi_init, pi_group_prior_a, pi_group_prior_b, group_vb_multiplier_init, updateGroupVb, nub_group, ssb_group_prior, normalize_group_vb, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L) {
    .Call(`_sblr_stblr_cpg_omp_csr_group_annot`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, group_index, ngroup, group_pi_init, pi_group_prior_a, pi_group_prior_b, group_vb_multiplier_init, updateGroupVb, nub_group, ssb_group_prior, normalize_group_vb, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves)
}

stblr_cpg_omp_csr_prior <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, use_pi_marker, pi_marker, use_vb_multiplier, vb_multiplier, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L) {
    .Call(`_sblr_stblr_cpg_omp_csr_prior`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, use_pi_marker, pi_marker, use_vb_multiplier, vb_multiplier, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves)
}

stblr_cpg_omp_csr_scheduled <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, wakeup_ld_neighbors, wakeup_diff_threshold, wakeup_max_neighbors, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds) {
    .Call(`_sblr_stblr_cpg_omp_csr_scheduled`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, wakeup_ld_neighbors, wakeup_diff_threshold, wakeup_max_neighbors, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds)
}

stblr_cpg_omp_bed_marker_sparse <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_update_prob, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, ncores, seed) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_sparse`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_update_prob, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, ncores, seed)
}

stblr_cpg_omp_bed_marker_scheduled <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, pi_prior_a, pi_prior_b, ncores, seed) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, pi_prior_a, pi_prior_b, ncores, seed)
}

stblr_cpg_omp_bed_marker_scheduled_chains <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, pi_prior_a, pi_prior_b, nchains, ncores, seed) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled_chains`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, pi_prior_a, pi_prior_b, nchains, ncores, seed)
}

stblr_cpg_omp_csr_sbayesrc <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_flat, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, selection_s_prior_scale = NULL, estimate_selection_s = FALSE, selection_s_init = 0.0, selection_s_prior = as.numeric( c(-3.0, 2.0)), selection_s_proposal_sd = 0.35, selection_s_log_h = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_sbayesrc`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_flat, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, selection_s_prior_scale, estimate_selection_s, selection_s_init, selection_s_prior, selection_s_proposal_sd, selection_s_log_h)
}

stblr_cpg_omp_csr_sbayesrc_block_eigen <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_flat, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, selection_s_prior_scale = NULL, estimate_selection_s = FALSE, selection_s_init = 0.0, selection_s_prior = as.numeric( c(-3.0, 2.0)), selection_s_proposal_sd = 0.35, selection_s_log_h = NULL, bed_files = as.character( c()), n_bed = 0L, cls = NULL, rows = NULL, af = as.numeric( c()), block_start = as.integer( c()), eigen_filter = "hard_truncate", eigen_tau = 0.01, eigen_eta = 0.0) {
    .Call(`_sblr_stblr_cpg_omp_csr_sbayesrc_block_eigen`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_flat, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, selection_s_prior_scale, estimate_selection_s, selection_s_init, selection_s_prior, selection_s_proposal_sd, selection_s_log_h, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta)
}

stblr_cpg_omp_bed_marker_scheduled_chains_bayesr <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, c, alpha, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, nchains, ncores, seed) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled_chains_bayesr`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, c, alpha, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, nchains, ncores, seed)
}

stblr_cpg_omp_bed_marker_scheduled_chains_bayesrc <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, A, gamma, annot_alpha_init, annot_sigma_sq_alpha_init, intercept_flat = TRUE, sigmaSqAlpha_a = 2.0, sigmaSqAlpha_b = 2.0, pi_floor = 1e-12, nub = 4.0, nue = 4.0, updateAlpha = TRUE, updateB = TRUE, updateE = TRUE, annot_alpha_update_every = 10L, adjE = 0.9, nit = 1000L, nburn = 100L, nthin = 1L, rebuild_every = 100L, return_wy = TRUE, return_r = TRUE, read_block_size = 256L, nchains = 1L, keep_chains = FALSE, ncores = 1L, seed = 10L) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled_chains_bayesrc`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, A, gamma, annot_alpha_init, annot_sigma_sq_alpha_init, intercept_flat, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, annot_alpha_update_every, adjE, nit, nburn, nthin, rebuild_every, return_wy, return_r, read_block_size, nchains, keep_chains, ncores, seed)
}

