# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blr_phase3_seed_v1_internal <- function(user_seed, analysis_mode, trait_id, chain_index) {
    .Call(`_sblr_blr_phase3_seed_v1_internal`, user_seed, analysis_mode, trait_id, chain_index)
}

blr_scalar_seeds_cpp <- function(seed, ntraits, nchains, chain_seeds) {
    .Call(`_sblr_blr_scalar_seeds_cpp`, seed, ntraits, nchains, chain_seeds)
}

mtblr_phase4a_pattern_contract_internal <- function(score, marker_sum_squares, marker_covariance, residual_covariance, activity_pattern_probability) {
    .Call(`_sblr_mtblr_phase4a_pattern_contract_internal`, score, marker_sum_squares, marker_covariance, residual_covariance, activity_pattern_probability)
}

mtblr_phase4b_residual_covariance_contract_internal <- function(residual, prior_df, prior_scale, draws, seed) {
    .Call(`_sblr_mtblr_phase4b_residual_covariance_contract_internal`, residual, prior_df, prior_scale, draws, seed)
}

mtblr_phase4a_cheng_bed_internal <- function(bed_files, source_sample_count, selected_columns, selected_rows, allele_frequency, phenotype, initial_residual_covariance, initial_marker_covariance, initial_activity_pattern_probability, activity_pattern_dirichlet_prior, marker_covariance_prior_df, marker_covariance_prior_scale, update_marker_covariance, update_activity_pattern_probability, update_residual_covariance, residual_covariance_prior_df, residual_covariance_prior_scale, burn_in_iterations, sampling_iterations, chains, cores, execution_contract) {
    .Call(`_sblr_mtblr_phase4a_cheng_bed_internal`, bed_files, source_sample_count, selected_columns, selected_rows, allele_frequency, phenotype, initial_residual_covariance, initial_marker_covariance, initial_activity_pattern_probability, activity_pattern_dirichlet_prior, marker_covariance_prior_df, marker_covariance_prior_scale, update_marker_covariance, update_activity_pattern_probability, update_residual_covariance, residual_covariance_prior_df, residual_covariance_prior_scale, burn_in_iterations, sampling_iterations, chains, cores, execution_contract)
}

readLD_to_CSR_R <- function(filenameSEXP, mchrSEXP, msizeSEXP, thresholdSEXP, onebasedSEXP) {
    .Call(`_sblr_readLD_to_CSR_R`, filenameSEXP, mchrSEXP, msizeSEXP, thresholdSEXP, onebasedSEXP)
}

mtblr_cpg_omp_csr <- function(wy, ww, yy, b_init, ld_prefix, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_cpg_omp_csr`, wy, ww, yy, b_init, ld_prefix, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, seed, method)
}

bed_xtx_xty <- function(bed_file, n, cls, af, y, rows = NULL, scale = TRUE, nthreads = 1L, MG = 64L, JB = 1024L, TB = 32L) {
    .Call(`_sblr_bed_xtx_xty`, bed_file, n, cls, af, y, rows, scale, nthreads, MG, JB, TB)
}

mtblr <- function(wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr`, wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_csr_internal <- function(wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_csr_internal`, wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_block_eigen_internal <- function(wy, yy, b, operator_descriptors, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method = 4L) {
    .Call(`_sblr_mtblr_block_eigen_internal`, wy, yy, b, operator_descriptors, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_csr_raw_internal <- function(wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_csr_raw_internal`, wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_csr_chains_raw_internal <- function(wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, joint_component, joint_multiplier, joint_names, component_count, marker_scale, component_init, pi_prior, beta_init, state_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance = FALSE, convergence_probability = FALSE, convergence_annotations = FALSE, convergence_full_probability = FALSE, convergence_markers = NULL, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE) {
    .Call(`_sblr_mtblr_csr_chains_raw_internal`, wy, ww, yy, b, ld_prefixes, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, joint_component, joint_multiplier, joint_names, component_count, marker_scale, component_init, pi_prior, beta_init, state_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance, convergence_probability, convergence_annotations, convergence_full_probability, convergence_markers, convergence_b, convergence_d, convergence_component)
}

mtblr_block_eigen_raw_internal <- function(wy, yy, b, operator_descriptors, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method = 4L) {
    .Call(`_sblr_mtblr_block_eigen_raw_internal`, wy, yy, b, operator_descriptors, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

mtblr_block_eigen_chains_raw_internal <- function(wy, yy, b, operator_descriptors, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, joint_component, joint_multiplier, joint_names, component_count, marker_scale, component_init, pi_prior, beta_init, state_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance = FALSE, convergence_probability = FALSE, convergence_annotations = FALSE, convergence_full_probability = FALSE, convergence_markers = NULL, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE) {
    .Call(`_sblr_mtblr_block_eigen_chains_raw_internal`, wy, yy, b, operator_descriptors, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, joint_component, joint_multiplier, joint_names, component_count, marker_scale, component_init, pi_prior, beta_init, state_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance, convergence_probability, convergence_annotations, convergence_full_probability, convergence_markers, convergence_b, convergence_d, convergence_component)
}

mtblr_bed_marker_contract_internal <- function(score, xx, B, E, models, pi) {
    .Call(`_sblr_mtblr_bed_marker_contract_internal`, score, xx, B, E, models, pi)
}

mtblr_bayesr_marker_contract_internal <- function(score, diagonal, B, E, patterns, component, multiplier, state_names, component_count, pi, marker_scale) {
    .Call(`_sblr_mtblr_bayesr_marker_contract_internal`, score, diagonal, B, E, patterns, component, multiplier, state_names, component_count, pi, marker_scale)
}

mtblr_bed_internal <- function(bed_files, n_bed, cls, rows, af, Y, beta_init, b_init, state_init, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, residual_covariance, nit, nburn, nthin, seed, method = 4L) {
    .Call(`_sblr_mtblr_bed_internal`, bed_files, n_bed, cls, rows, af, Y, beta_init, b_init, state_init, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, residual_covariance, nit, nburn, nthin, seed, method)
}

mtblr_bed_chains_internal <- function(bed_files, n_bed, cls, rows, af, Y, beta_init, b_init, state_init, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, residual_covariance, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, keep_chains, joint_component, joint_multiplier, joint_names, component_count, marker_scale, pi_prior, component_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance = FALSE, convergence_probability = FALSE, convergence_annotations = FALSE, convergence_full_probability = FALSE, convergence_markers = NULL, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE) {
    .Call(`_sblr_mtblr_bed_chains_internal`, bed_files, n_bed, cls, rows, af, Y, beta_init, b_init, state_init, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, residual_covariance, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, keep_chains, joint_component, joint_multiplier, joint_names, component_count, marker_scale, pi_prior, component_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance, convergence_probability, convergence_annotations, convergence_full_probability, convergence_markers, convergence_b, convergence_d, convergence_component)
}

mtblr_bed_convergence_trace_internal <- function(bed_files, n_bed, cls, rows, af, Y, beta_init, b_init, state_init, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, residual_covariance, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, keep_chains, joint_component, joint_multiplier, joint_names, component_count, marker_scale, pi_prior, component_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance = FALSE, convergence_probability = FALSE, convergence_annotations = FALSE, convergence_full_probability = FALSE, convergence_markers = NULL, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE) {
    .Call(`_sblr_mtblr_bed_convergence_trace_internal`, bed_files, n_bed, cls, rows, af, Y, beta_init, b_init, state_init, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, residual_covariance, nit, nburn, nthin, seed, method, nchains, ncores, chain_seeds, keep_chains, joint_component, joint_multiplier, joint_names, component_count, marker_scale, pi_prior, component_init, annotations, alpha_init, sigma_alpha_init, pattern_pi_init, pattern_pi_prior, updateAlpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, pi_floor, alpha_update_every, convergence_covariance, convergence_probability, convergence_annotations, convergence_full_probability, convergence_markers, convergence_b, convergence_d, convergence_component)
}

mtblr_eigen <- function(wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method) {
    .Call(`_sblr_mtblr_eigen`, wy, ww, yy, b, XXvalues, XXindices, sets, B, E, ssb_prior, sse_prior, models, pi, nub, nue, updateB, updateE, updatePi, n, nit, nburn, nthin, seed, method)
}

test_read_bedfiles_to_packed_matrix <- function(bedfiles, n, rows, cls) {
    .Call(`_sblr_test_read_bedfiles_to_packed_matrix`, bedfiles, n, rows, cls)
}

test_read_bedfiles_to_dense_matrix <- function(bedfiles, n, rows, cls) {
    .Call(`_sblr_test_read_bedfiles_to_dense_matrix`, bedfiles, n, rows, cls)
}

bed_pairwise_xtx_check <- function(bed_files, n, cls, pairs, rows = NULL, af = NULL, scale = TRUE) {
    .Call(`_sblr_bed_pairwise_xtx_check`, bed_files, n, cls, pairs, rows, af, scale)
}

bed_score_from_b_check <- function(bed_files, n, cls, y, b, rows = NULL, af = NULL, scale = TRUE) {
    .Call(`_sblr_bed_score_from_b_check`, bed_files, n, cls, y, b, rows, af, scale)
}

sparseLD_thread_info <- function(nthreads = 0L) {
    .Call(`_sblr_sparseLD_thread_info`, nthreads)
}

sparseLD_stream_CSR <- function(bed_files, n, cls, out_prefix, rows = NULL, af = NULL, pos_bp = NULL, max_distance_bp = 1000000L, max_distance_variants = 1000L, r2_threshold = 0.01, block_size = 1024L, nthreads = 1L) {
    .Call(`_sblr_sparseLD_stream_CSR`, bed_files, n, cls, out_prefix, rows, af, pos_bp, max_distance_bp, max_distance_variants, r2_threshold, block_size, nthreads)
}

sparseLD_to_CSR <- function(bed_files, n, cls, rows = NULL, af = NULL, pos_bp = NULL, max_distance_bp = 1000000L, max_distance_variants = 1000L, r2_threshold = 0.01, block_size = 1024L, nthreads = 1L) {
    .Call(`_sblr_sparseLD_to_CSR`, bed_files, n, cls, rows, af, pos_bp, max_distance_bp, max_distance_variants, r2_threshold, block_size, nthreads)
}

sparseLD_write_CSR <- function(bed_files, n, cls, out_prefix, rows = NULL, af = NULL, pos_bp = NULL, max_distance_bp = 1000000L, max_distance_variants = 1000L, r2_threshold = 0.01, block_size = 1024L, nthreads = 1L) {
    .Call(`_sblr_sparseLD_write_CSR`, bed_files, n, cls, out_prefix, rows, af, pos_bp, max_distance_bp, max_distance_variants, r2_threshold, block_size, nthreads)
}

sparseLD_read_CSR <- function(prefix, one_based = TRUE) {
    .Call(`_sblr_sparseLD_read_CSR`, prefix, one_based)
}

stblr_color_blocks_from_ld <- function(sets, ld_row_ptr, ld_col_idx, ld_values, ld_col_idx_one_based = TRUE, ld_abs_threshold = 0.01, ld_r2_threshold = 0.0) {
    .Call(`_sblr_stblr_color_blocks_from_ld`, sets, ld_row_ptr, ld_col_idx, ld_values, ld_col_idx_one_based, ld_abs_threshold, ld_r2_threshold)
}

stblr_block_eigen_contract_internal <- function(bed_files, n_bed, cls, rows, af, block_start, wy, effects, eigen_filter = "hard_truncate", eigen_tau = 0.01, eigen_eta = 0.0, validation_mutation = "") {
    .Call(`_sblr_stblr_block_eigen_contract_internal`, bed_files, n_bed, cls, rows, af, block_start, wy, effects, eigen_filter, eigen_tau, eigen_eta, validation_mutation)
}

stblr_block_low_rank_contract_internal <- function(bed_files, n_bed, cls, rows, af, block_start, wy, effects, eigen_prop = 0.995, yy = 1.0, residual_perturbation = 0.0) {
    .Call(`_sblr_stblr_block_low_rank_contract_internal`, bed_files, n_bed, cls, rows, af, block_start, wy, effects, eigen_prop, yy, residual_perturbation)
}

.stblr_block_ve_decision <- function(mode, iteration, genetic_variance, effect_ss, resam_thresh, permanent_selected = FALSE) {
    .Call(`_sblr_stblr_block_ve_decision_internal`, mode, iteration, genetic_variance, effect_ss, resam_thresh, permanent_selected)
}

.stblr_block_ve_draw_parameters <- function(residual_ss, phenotype_variance, nue, rank) {
    .Call(`_sblr_stblr_block_ve_draw_parameters_internal`, residual_ss, phenotype_variance, nue, rank)
}

.stblr_block_ve_ratio_accepted <- function(ratio, minimum) {
    .Call(`_sblr_stblr_block_ve_ratio_accepted_internal`, ratio, minimum)
}

stblr_cpg_omp_block_eigen_logvar_bayesc <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, convergence_markers, convergence_b, convergence_d, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta, representation, eigen_prop, low_rank_residual_rebuild_every, annotation, theta_init, theta_prior_sd, updateTheta) {
    .Call(`_sblr_stblr_cpg_omp_block_eigen_logvar_bayesc`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, convergence_markers, convergence_b, convergence_d, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta, representation, eigen_prop, low_rank_residual_rebuild_every, annotation, theta_init, theta_prior_sd, updateTheta)
}

stblr_cpg_omp_block_eigen_logvar_bayesr <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, convergence_markers, convergence_probability, convergence_b, convergence_d, convergence_component, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta, representation, eigen_prop, low_rank_residual_rebuild_every, block_residual_config, annotation, theta_init, theta_prior_sd, updateTheta) {
    .Call(`_sblr_stblr_cpg_omp_block_eigen_logvar_bayesr`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, convergence_markers, convergence_probability, convergence_b, convergence_d, convergence_component, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta, representation, eigen_prop, low_rank_residual_rebuild_every, block_residual_config, annotation, theta_init, theta_prior_sd, updateTheta)
}

stblr_cpg_omp_csr <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, maf_effect_s_prior_scale = NULL, estimate_maf_effect_s = FALSE, maf_effect_s_init = 0.0, maf_effect_s_prior = as.numeric( c(-3.0, 2.0)), maf_effect_s_proposal_sd = 0.35, maf_effect_s_log_h = NULL, convergence_markers = as.integer( c()), convergence_b = FALSE, convergence_d = FALSE, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, maf_effect_s_prior_scale, estimate_maf_effect_s, maf_effect_s_init, maf_effect_s_prior, maf_effect_s_proposal_sd, maf_effect_s_log_h, convergence_markers, convergence_b, convergence_d, execution_contract)
}

stblr_cpg_omp_csr_block_eigen <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, maf_effect_s_prior_scale = NULL, estimate_maf_effect_s = FALSE, maf_effect_s_init = 0.0, maf_effect_s_prior = as.numeric( c(-3.0, 2.0)), maf_effect_s_proposal_sd = 0.35, maf_effect_s_log_h = NULL, convergence_markers = as.integer( c()), convergence_b = FALSE, convergence_d = FALSE, bed_files = as.character( c()), n_bed = 0L, cls = NULL, rows = NULL, af = as.numeric( c()), block_start = as.integer( c()), eigen_filter = "hard_truncate", eigen_tau = 0.01, eigen_eta = 0.0, representation = "dense_reconstructed", eigen_prop = 0.995, low_rank_residual_rebuild_every = 100L, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_block_eigen`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, maf_effect_s_prior_scale, estimate_maf_effect_s, maf_effect_s_init, maf_effect_s_prior, maf_effect_s_proposal_sd, maf_effect_s_log_h, convergence_markers, convergence_b, convergence_d, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta, representation, eigen_prop, low_rank_residual_rebuild_every, execution_contract)
}

stblr_low_rank_bayesc_hot_path_benchmark_internal <- function(markers = 1000L, rank = 250L, repetitions = 7L, warmup = 2L, seed = 7301L) {
    .Call(`_sblr_stblr_low_rank_bayesc_hot_path_benchmark_internal`, markers, rank, repetitions, warmup, seed)
}

stblr_learned_logistic_pi_draws_internal <- function(state, offset, pi_init, pi_prior_a, pi_prior_b, draws, burnin, seed) {
    .Call(`_sblr_stblr_learned_logistic_pi_draws_internal`, state, offset, pi_init, pi_prior_a, pi_prior_b, draws, burnin, seed)
}

stblr_learned_logistic_eta_logpost_internal <- function(A, eta, state, base_pi, sigma_eta) {
    .Call(`_sblr_stblr_learned_logistic_eta_logpost_internal`, A, eta, state, base_pi, sigma_eta)
}

stblr_learned_logistic_probability_terms_internal <- function(predictor) {
    .Call(`_sblr_stblr_learned_logistic_probability_terms_internal`, predictor)
}

stblr_cpg_omp_csr_annot <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, A, learn_pi_annot, learn_vb_annot, eta_pi_init, eta_vb_init, sigma_eta_pi, sigma_eta_vb, rw_sd_eta_pi, rw_sd_eta_vb, annot_update_every, vb_multiplier_min, vb_multiplier_max, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, convergence_markers = as.integer( c()), convergence_annotations = FALSE, convergence_b = FALSE, convergence_d = FALSE, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_annot`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, A, learn_pi_annot, learn_vb_annot, eta_pi_init, eta_vb_init, sigma_eta_pi, sigma_eta_vb, rw_sd_eta_pi, rw_sd_eta_vb, annot_update_every, vb_multiplier_min, vb_multiplier_max, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, convergence_markers, convergence_annotations, convergence_b, convergence_d, execution_contract)
}

stblr_cpg_omp_csr_bayesr <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start = 0L, updateE_every = 1L, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, maf_effect_s_prior_scale = NULL, estimate_maf_effect_s = FALSE, maf_effect_s_init = 0.0, maf_effect_s_prior = as.numeric( c(-3.0, 2.0)), maf_effect_s_proposal_sd = 0.35, maf_effect_s_log_h = NULL, convergence_markers = as.integer( c()), convergence_probability = FALSE, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_bayesr`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, maf_effect_s_prior_scale, estimate_maf_effect_s, maf_effect_s_init, maf_effect_s_prior, maf_effect_s_proposal_sd, maf_effect_s_log_h, convergence_markers, convergence_probability, convergence_b, convergence_d, convergence_component, execution_contract)
}

stblr_cpg_omp_csr_bayesr_block_eigen <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start = 0L, updateE_every = 1L, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, maf_effect_s_prior_scale = NULL, estimate_maf_effect_s = FALSE, maf_effect_s_init = 0.0, maf_effect_s_prior = as.numeric( c(-3.0, 2.0)), maf_effect_s_proposal_sd = 0.35, maf_effect_s_log_h = NULL, convergence_markers = as.integer( c()), convergence_probability = FALSE, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE, bed_files = as.character( c()), n_bed = 0L, cls = NULL, rows = NULL, af = as.numeric( c()), block_start = as.integer( c()), eigen_filter = "hard_truncate", eigen_tau = 0.01, eigen_eta = 0.0, representation = "dense_reconstructed", eigen_prop = 0.995, low_rank_residual_rebuild_every = 100L, block_residual_config = NULL, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_bayesr_block_eigen`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, maf_effect_s_prior_scale, estimate_maf_effect_s, maf_effect_s_init, maf_effect_s_prior, maf_effect_s_proposal_sd, maf_effect_s_log_h, convergence_markers, convergence_probability, convergence_b, convergence_d, convergence_component, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta, representation, eigen_prop, low_rank_residual_rebuild_every, block_residual_config, execution_contract)
}

stblr_low_rank_bayesr_hot_path_benchmark_internal <- function(markers = 1000L, rank = 250L, repetitions = 7L, warmup = 2L, seed = 7301L) {
    .Call(`_sblr_stblr_low_rank_bayesr_hot_path_benchmark_internal`, markers, rank, repetitions, warmup, seed)
}

stblr_cpg_omp_csr_group_annot <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, group_index, ngroup, group_pi_init, pi_group_prior_a, pi_group_prior_b, group_vb_multiplier_init, updateGroupVb, nub_group, ssb_group_prior, normalize_group_vb, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, convergence_markers = as.integer( c()), convergence_annotations = FALSE, convergence_b = FALSE, convergence_d = FALSE) {
    .Call(`_sblr_stblr_cpg_omp_csr_group_annot`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, group_index, ngroup, group_pi_init, pi_group_prior_a, pi_group_prior_b, group_vb_multiplier_init, updateGroupVb, nub_group, ssb_group_prior, normalize_group_vb, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, convergence_markers, convergence_annotations, convergence_b, convergence_d)
}

stblr_cpg_omp_csr_logvar_bayesc <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, annotation, theta_init, theta_prior_sd, updateTheta, convergence_markers, convergence_b, convergence_d) {
    .Call(`_sblr_stblr_cpg_omp_csr_logvar_bayesc`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, annotation, theta_init, theta_prior_sd, updateTheta, convergence_markers, convergence_b, convergence_d)
}

stblr_cpg_omp_csr_logvar_bayesr <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, annotation, theta_init, theta_prior_sd, updateTheta, convergence_markers, convergence_probability, convergence_b, convergence_d, convergence_component) {
    .Call(`_sblr_stblr_cpg_omp_csr_logvar_bayesr`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, mixture_var, alpha, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateE_start, updateE_every, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, annotation, theta_init, theta_prior_sd, updateTheta, convergence_markers, convergence_probability, convergence_b, convergence_d, convergence_component)
}

stblr_cpg_omp_csr_prior <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, use_pi_marker, pi_marker, use_vb_multiplier, vb_multiplier, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, convergence_markers = as.integer( c()), convergence_b = FALSE, convergence_d = FALSE, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_prior`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, use_pi_marker, pi_marker, use_vb_multiplier, vb_multiplier, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, convergence_markers, convergence_b, convergence_d, execution_contract)
}

stblr_cpg_omp_csr_scheduled <- function(wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, wakeup_ld_neighbors, wakeup_diff_threshold, wakeup_max_neighbors, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, convergence_markers = as.integer( c()), convergence_b = FALSE, convergence_d = FALSE) {
    .Call(`_sblr_stblr_cpg_omp_csr_scheduled`, wy, ww, yy, b_init, d_init, use_d_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, n, nit, nburn, nthin, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, wakeup_ld_neighbors, wakeup_diff_threshold, wakeup_max_neighbors, pi_prior_a, pi_prior_b, ncores, seed, nchains, keep_chains, chain_seeds, convergence_markers, convergence_b, convergence_d)
}

stblr_cpg_omp_bed_marker_sparse <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_update_prob, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, ncores, seed) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_sparse`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_update_prob, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, ncores, seed)
}

stblr_cpg_omp_bed_marker_scheduled <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, pi_prior_a, pi_prior_b, ncores, seed) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, pi_prior_a, pi_prior_b, ncores, seed)
}

stblr_cpg_omp_bed_marker_scheduled_chains <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, pi_prior_a, pi_prior_b, nchains, ncores, seed, chain_seeds = as.integer( c()), convergence_markers = as.integer( c()), convergence_b = FALSE, convergence_d = FALSE, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled_chains`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, pi_prior_a, pi_prior_b, nchains, ncores, seed, chain_seeds, convergence_markers, convergence_b, convergence_d, execution_contract)
}

st_logvar_eta_q_internal <- function(annotation, theta) {
    .Call(`_sblr_st_logvar_eta_q_internal`, annotation, theta)
}

st_logvar_loglik_bayesc_internal <- function(theta, annotation, effect, state, marker_variance) {
    .Call(`_sblr_st_logvar_loglik_bayesc_internal`, theta, annotation, effect, state, marker_variance)
}

st_logvar_loglik_bayesr_internal <- function(theta, annotation, effect, component, marker_variance, gamma) {
    .Call(`_sblr_st_logvar_loglik_bayesr_internal`, theta, annotation, effect, component, marker_variance, gamma)
}

st_logvar_ess_fixture_internal <- function(theta, annotation, effect, state, marker_variance, theta_prior_sd = 0.7, updates = 1L, seed = 1L, empty_active_set = FALSE, model = "bayesc", gamma = NULL) {
    .Call(`_sblr_st_logvar_ess_fixture_internal`, theta, annotation, effect, state, marker_variance, theta_prior_sd, updates, seed, empty_active_set, model, gamma)
}

.st_bayesrc_truncated_normal_draws <- function(location, draws, seed) {
    .Call(`_sblr_st_bayesrc_truncated_normal_draws_test`, location, draws, seed)
}

.st_bayesrc_annotation_update <- function(annotation, component_numeric, alpha, sigma_sq_alpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, seed) {
    .Call(`_sblr_st_bayesrc_annotation_update_test`, annotation, component_numeric, alpha, sigma_sq_alpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, seed)
}

.st_bayesrc_alpha_conditional_moments <- function(annotation, latent, alpha, sigma_sq_alpha, intercept_mean, intercept_sd) {
    .Call(`_sblr_st_bayesrc_alpha_conditional_moments_test`, annotation, latent, alpha, sigma_sq_alpha, intercept_mean, intercept_sd)
}

.st_bayesrc_sigma_sq_alpha_draws <- function(alpha_non_intercept, prior_a, prior_b, draws, seed) {
    .Call(`_sblr_st_bayesrc_sigma_sq_alpha_draws_test`, alpha_non_intercept, prior_a, prior_b, draws, seed)
}

.st_bayesrc_frozen_hierarchy_chains <- function(annotation, component_numeric, alpha_initial, sigma_initial, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, probability_floor, iterations, chain_seeds, cores) {
    .Call(`_sblr_st_bayesrc_frozen_hierarchy_chains_test`, annotation, component_numeric, alpha_initial, sigma_initial, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, probability_floor, iterations, chain_seeds, cores)
}

.st_bayesrc_selection_math <- function(annotation, eligible, latent, alpha, delta, pi_a, tau2, a_pi, b_pi, a_tau, b_tau, intercept_prior_resolved, probability_floor) {
    .Call(`_sblr_st_bayesrc_selection_math_test`, annotation, eligible, latent, alpha, delta, pi_a, tau2, a_pi, b_pi, a_tau, b_tau, intercept_prior_resolved, probability_floor)
}

.st_bayesrc_selection_hierarchy <- function(annotation, eligible, outcome, alpha_initial, delta_initial, pi_a_initial, tau2_initial, a_pi, b_pi, a_tau, b_tau, intercept_prior_resolved, probability_floor, iterations, burn, seed, fixed_delta) {
    .Call(`_sblr_st_bayesrc_selection_hierarchy_test`, annotation, eligible, outcome, alpha_initial, delta_initial, pi_a_initial, tau2_initial, a_pi, b_pi, a_tau, b_tau, intercept_prior_resolved, probability_floor, iterations, burn, seed, fixed_delta)
}

.st_bayesrc_pairwise_conditional <- function(prior_i, prior_j, gamma, marker_variance, prior_scale_i, prior_scale_j, residual_variance, diagonal_i, diagonal_j, cross_product, score_i, score_j) {
    .Call(`_sblr_st_bayesrc_pairwise_conditional_test`, prior_i, prior_j, gamma, marker_variance, prior_scale_i, prior_scale_j, residual_variance, diagonal_i, diagonal_j, cross_product, score_i, score_j)
}

.st_bayesrc_information_summary <- function(log_probability, prior_probability, component, annotation) {
    .Call(`_sblr_st_bayesrc_information_summary_internal`, log_probability, prior_probability, component, annotation)
}

stblr_cpg_omp_csr_sbayesrc <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_prior_resolved, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, maf_effect_s_prior_scale = NULL, estimate_maf_effect_s = FALSE, maf_effect_s_init = 0.0, maf_effect_s_prior = as.numeric( c(-3.0, 2.0)), maf_effect_s_proposal_sd = 0.35, maf_effect_s_log_h = NULL, convergence_markers = as.integer( c()), convergence_annotations = FALSE, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE) {
    .Call(`_sblr_stblr_cpg_omp_csr_sbayesrc`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_prior_resolved, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, maf_effect_s_prior_scale, estimate_maf_effect_s, maf_effect_s_init, maf_effect_s_prior, maf_effect_s_proposal_sd, maf_effect_s_log_h, convergence_markers, convergence_annotations, convergence_b, convergence_d, convergence_component)
}

.st_sbayesrc_selection_csr <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, delta_init, pi_A_init, tau2_init, a_pi, b_pi, a_tau, b_tau, fixed_delta, update_hierarchy, update_pi_A, update_tau2, intercept_prior_resolved, pi_floor, nub, nue, updateB, updateE, adjE, n, nit, nburn, nthin, ncores, seed, nchains = 1L, chain_seeds = NULL, selection_enabled = TRUE, information_diagnostics = FALSE) {
    .Call(`_sblr_st_sbayesrc_selection_csr_internal`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, ld_prefix, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, delta_init, pi_A_init, tau2_init, a_pi, b_pi, a_tau, b_tau, fixed_delta, update_hierarchy, update_pi_A, update_tau2, intercept_prior_resolved, pi_floor, nub, nue, updateB, updateE, adjE, n, nit, nburn, nthin, ncores, seed, nchains, chain_seeds, selection_enabled, information_diagnostics)
}

stblr_cpg_omp_csr_sbayesrc_block_eigen <- function(wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_prior_resolved, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains = 1L, keep_chains = FALSE, chain_seeds = NULL, updateLDswap = FALSE, ld_swap_prob = 0.05, ld_swap_r2 = 0.8, ld_swap_max_friends = 50L, ld_swap_moves = 1L, maf_effect_s_prior_scale = NULL, estimate_maf_effect_s = FALSE, maf_effect_s_init = 0.0, maf_effect_s_prior = as.numeric( c(-3.0, 2.0)), maf_effect_s_proposal_sd = 0.35, maf_effect_s_log_h = NULL, convergence_markers = as.integer( c()), convergence_annotations = FALSE, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE, bed_files = as.character( c()), n_bed = 0L, cls = NULL, rows = NULL, af = as.numeric( c()), block_start = as.integer( c()), eigen_filter = "hard_truncate", eigen_tau = 0.01, eigen_eta = 0.0, representation = "dense_reconstructed", eigen_prop = 0.995, low_rank_residual_config = NULL) {
    .Call(`_sblr_stblr_cpg_omp_csr_sbayesrc_block_eigen`, wy, ww, yy, b_init, comp_init, use_comp_init, r_init, use_r_init, rebuild_r_before_updateE, B, E, ssb_prior, sse_prior, A, gamma, alpha_init, sigmaSqAlpha_init, intercept_prior_resolved, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, alpha_update_every, adjE, n, nit, nburn, nthin, ncores, seed, nchains, keep_chains, chain_seeds, updateLDswap, ld_swap_prob, ld_swap_r2, ld_swap_max_friends, ld_swap_moves, maf_effect_s_prior_scale, estimate_maf_effect_s, maf_effect_s_init, maf_effect_s_prior, maf_effect_s_proposal_sd, maf_effect_s_log_h, convergence_markers, convergence_annotations, convergence_b, convergence_d, convergence_component, bed_files, n_bed, cls, rows, af, block_start, eigen_filter, eigen_tau, eigen_eta, representation, eigen_prop, low_rank_residual_config)
}

.st_sbayesrc_invalid_scale_diagnostic_fixture <- function(path) {
    invisible(.Call(`_sblr_st_sbayesrc_invalid_scale_diagnostic_fixture`, path))
}

stblr_cpg_omp_bed_marker_scheduled_chains_bayesr <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, c, alpha, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, nchains, ncores, seed, chain_seeds = as.integer( c()), convergence_markers = as.integer( c()), convergence_probability = FALSE, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE, execution_contract = NULL) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled_chains_bayesr`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, pi, c, alpha, nub, nue, updateB, updateE, updatePi, adjE, nit, nburn, nthin, rebuild_every, full_sweep_every, null_skip_base, null_skip_max, candidate_threshold, candidate_lifetime, skip_nulls_burnin_only, return_wy, return_r, read_block_size, progress_every, nchains, ncores, seed, chain_seeds, convergence_markers, convergence_probability, convergence_b, convergence_d, convergence_component, execution_contract)
}

.st_bayesrc_tempered_probabilities <- function(annotation, alpha, baseline_intercept, coupling, probability_floor) {
    .Call(`_sblr_st_bayesrc_tempered_probabilities_test`, annotation, alpha, baseline_intercept, coupling, probability_floor)
}

.st_bayesrc_tempered_annotation_update <- function(annotation, component_numeric, alpha, sigma_sq_alpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, baseline_intercept, coupling, seed) {
    .Call(`_sblr_st_bayesrc_tempered_annotation_update_test`, annotation, component_numeric, alpha, sigma_sq_alpha, intercept_prior_resolved, sigma_alpha_a, sigma_alpha_b, baseline_intercept, coupling, seed)
}

.st_bayesrc_coupling_swap_log_ratio <- function(annotation, alpha_lower, component_lower_numeric, alpha_upper, component_upper_numeric, baseline_intercept, coupling_lower, coupling_upper, probability_floor) {
    .Call(`_sblr_st_bayesrc_coupling_swap_log_ratio_test`, annotation, alpha_lower, component_lower_numeric, alpha_upper, component_upper_numeric, baseline_intercept, coupling_lower, coupling_upper, probability_floor)
}

stblr_cpg_omp_bed_marker_scheduled_chains_bayesrc <- function(bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, A, gamma, annot_alpha_init, annot_sigma_sq_alpha_init, intercept_prior_resolved, sigmaSqAlpha_a = 2.0, sigmaSqAlpha_b = 2.0, pi_floor = 1e-12, nub = 4.0, nue = 4.0, updateAlpha = TRUE, updateB = TRUE, updateE = TRUE, annot_alpha_update_every = 10L, adjE = 0.9, nit = 1000L, nburn = 100L, nthin = 1L, rebuild_every = 100L, return_wy = TRUE, return_r = TRUE, read_block_size = 256L, nchains = 1L, keep_chains = FALSE, ncores = 1L, seed = 10L, chain_seeds = as.integer( c()), convergence_markers = as.integer( c()), convergence_annotations = FALSE, convergence_b = FALSE, convergence_d = FALSE, convergence_component = FALSE) {
    .Call(`_sblr_stblr_cpg_omp_bed_marker_scheduled_chains_bayesrc`, bed_files, n, cls, y, b_init, sets, rows, af, scale, B, E, ssb_prior, sse_prior, A, gamma, annot_alpha_init, annot_sigma_sq_alpha_init, intercept_prior_resolved, sigmaSqAlpha_a, sigmaSqAlpha_b, pi_floor, nub, nue, updateAlpha, updateB, updateE, annot_alpha_update_every, adjE, nit, nburn, nthin, rebuild_every, return_wy, return_r, read_block_size, nchains, keep_chains, ncores, seed, chain_seeds, convergence_markers, convergence_annotations, convergence_b, convergence_d, convergence_component)
}

